/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversityRouteImport } from './routes/university'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ForUniversitiesRouteImport } from './routes/for-universities'
import { Route as ForCompaniesRouteImport } from './routes/for-companies'
import { Route as ForCandidatesRouteImport } from './routes/for-candidates'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CandidateRouteImport } from './routes/candidate'
import { Route as BookDemoRouteImport } from './routes/book-demo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UniversityIndexRouteImport } from './routes/university.index'
import { Route as CompanyIndexRouteImport } from './routes/company.index'
import { Route as CandidateIndexRouteImport } from './routes/candidate.index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as UniversityStudentsRouteImport } from './routes/university.students'
import { Route as UniversitySettingsRouteImport } from './routes/university.settings'
import { Route as UniversityPartnershipsRouteImport } from './routes/university.partnerships'
import { Route as UniversityMessagesRouteImport } from './routes/university.messages'
import { Route as UniversityLeaderboardsRouteImport } from './routes/university.leaderboards'
import { Route as UniversityEvidenceRouteImport } from './routes/university.evidence'
import { Route as UniversityChallengesRouteImport } from './routes/university.challenges'
import { Route as UniversityCertificatesRouteImport } from './routes/university.certificates'
import { Route as UniversityAnalyticsRouteImport } from './routes/university.analytics'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as CompanyShortlistsRouteImport } from './routes/company.shortlists'
import { Route as CompanySettingsRouteImport } from './routes/company.settings'
import { Route as CompanyReportsRouteImport } from './routes/company.reports'
import { Route as CompanyMessagesRouteImport } from './routes/company.messages'
import { Route as CompanyLibraryRouteImport } from './routes/company.library'
import { Route as CompanyJobsRouteImport } from './routes/company.jobs'
import { Route as CompanyInterviewsRouteImport } from './routes/company.interviews'
import { Route as CompanyChallengeBuilderRouteImport } from './routes/company.challenge-builder'
import { Route as CompanyCandidatesRouteImport } from './routes/company.candidates'
import { Route as CompanyCampaignsRouteImport } from './routes/company.campaigns'
import { Route as CompanyBillingRouteImport } from './routes/company.billing'
import { Route as CompanyAnalyticsRouteImport } from './routes/company.analytics'
import { Route as CandidateSettingsRouteImport } from './routes/candidate.settings'
import { Route as CandidateRoadmapRouteImport } from './routes/candidate.roadmap'
import { Route as CandidateResultsRouteImport } from './routes/candidate.results'
import { Route as CandidateProfileRouteImport } from './routes/candidate.profile'
import { Route as CandidateNotificationsRouteImport } from './routes/candidate.notifications'
import { Route as CandidateMessagesRouteImport } from './routes/candidate.messages'
import { Route as CandidateJobsRouteImport } from './routes/candidate.jobs'
import { Route as CandidateInterviewRouteImport } from './routes/candidate.interview'
import { Route as CandidateChallengesRouteImport } from './routes/candidate.challenges'
import { Route as CandidateCertificatesRouteImport } from './routes/candidate.certificates'
import { Route as CandidateApplicationsRouteImport } from './routes/candidate.applications'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as CandidateJobsIndexRouteImport } from './routes/candidate.jobs.index'
import { Route as CandidateChallengesIndexRouteImport } from './routes/candidate.challenges.index'
import { Route as CandidateJobsIdRouteImport } from './routes/candidate.jobs.$id'
import { Route as CandidateChallengesIdRouteImport } from './routes/candidate.challenges.$id'

const UniversityRoute = UniversityRouteImport.update({
  id: '/university',
  path: '/university',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ForUniversitiesRoute = ForUniversitiesRouteImport.update({
  id: '/for-universities',
  path: '/for-universities',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCompaniesRoute = ForCompaniesRouteImport.update({
  id: '/for-companies',
  path: '/for-companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCandidatesRoute = ForCandidatesRouteImport.update({
  id: '/for-candidates',
  path: '/for-candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateRoute = CandidateRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDemoRoute = BookDemoRouteImport.update({
  id: '/book-demo',
  path: '/book-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityIndexRoute = UniversityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UniversityRoute,
} as any)
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanyRoute,
} as any)
const CandidateIndexRoute = CandidateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CandidateRoute,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityStudentsRoute = UniversityStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => UniversityRoute,
} as any)
const UniversitySettingsRoute = UniversitySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => UniversityRoute,
} as any)
const UniversityPartnershipsRoute = UniversityPartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => UniversityRoute,
} as any)
const UniversityMessagesRoute = UniversityMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => UniversityRoute,
} as any)
const UniversityLeaderboardsRoute = UniversityLeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => UniversityRoute,
} as any)
const UniversityEvidenceRoute = UniversityEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => UniversityRoute,
} as any)
const UniversityChallengesRoute = UniversityChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => UniversityRoute,
} as any)
const UniversityCertificatesRoute = UniversityCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => UniversityRoute,
} as any)
const UniversityAnalyticsRoute = UniversityAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => UniversityRoute,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyShortlistsRoute = CompanyShortlistsRouteImport.update({
  id: '/shortlists',
  path: '/shortlists',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanySettingsRoute = CompanySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyReportsRoute = CompanyReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyMessagesRoute = CompanyMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyLibraryRoute = CompanyLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyJobsRoute = CompanyJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyInterviewsRoute = CompanyInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyChallengeBuilderRoute = CompanyChallengeBuilderRouteImport.update({
  id: '/challenge-builder',
  path: '/challenge-builder',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyCandidatesRoute = CompanyCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyCampaignsRoute = CompanyCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyBillingRoute = CompanyBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyAnalyticsRoute = CompanyAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => CompanyRoute,
} as any)
const CandidateSettingsRoute = CandidateSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateRoadmapRoute = CandidateRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateResultsRoute = CandidateResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateNotificationsRoute = CandidateNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateMessagesRoute = CandidateMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateJobsRoute = CandidateJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateInterviewRoute = CandidateInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateChallengesRoute = CandidateChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateCertificatesRoute = CandidateCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateApplicationsRoute = CandidateApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => CandidateRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateJobsIndexRoute = CandidateJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CandidateJobsRoute,
} as any)
const CandidateChallengesIndexRoute =
  CandidateChallengesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CandidateChallengesRoute,
  } as any)
const CandidateJobsIdRoute = CandidateJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CandidateJobsRoute,
} as any)
const CandidateChallengesIdRoute = CandidateChallengesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CandidateChallengesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book-demo': typeof BookDemoRoute
  '/candidate': typeof CandidateRouteWithChildren
  '/company': typeof CompanyRouteWithChildren
  '/demo': typeof DemoRoute
  '/for-candidates': typeof ForCandidatesRoute
  '/for-companies': typeof ForCompaniesRoute
  '/for-universities': typeof ForUniversitiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/university': typeof UniversityRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/certificates': typeof CandidateCertificatesRoute
  '/candidate/challenges': typeof CandidateChallengesRouteWithChildren
  '/candidate/interview': typeof CandidateInterviewRoute
  '/candidate/jobs': typeof CandidateJobsRouteWithChildren
  '/candidate/messages': typeof CandidateMessagesRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/results': typeof CandidateResultsRoute
  '/candidate/roadmap': typeof CandidateRoadmapRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/company/analytics': typeof CompanyAnalyticsRoute
  '/company/billing': typeof CompanyBillingRoute
  '/company/campaigns': typeof CompanyCampaignsRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/challenge-builder': typeof CompanyChallengeBuilderRoute
  '/company/interviews': typeof CompanyInterviewsRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/library': typeof CompanyLibraryRoute
  '/company/messages': typeof CompanyMessagesRoute
  '/company/reports': typeof CompanyReportsRoute
  '/company/settings': typeof CompanySettingsRoute
  '/company/shortlists': typeof CompanyShortlistsRoute
  '/p/$id': typeof PIdRoute
  '/university/analytics': typeof UniversityAnalyticsRoute
  '/university/certificates': typeof UniversityCertificatesRoute
  '/university/challenges': typeof UniversityChallengesRoute
  '/university/evidence': typeof UniversityEvidenceRoute
  '/university/leaderboards': typeof UniversityLeaderboardsRoute
  '/university/messages': typeof UniversityMessagesRoute
  '/university/partnerships': typeof UniversityPartnershipsRoute
  '/university/settings': typeof UniversitySettingsRoute
  '/university/students': typeof UniversityStudentsRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/candidate/': typeof CandidateIndexRoute
  '/company/': typeof CompanyIndexRoute
  '/university/': typeof UniversityIndexRoute
  '/candidate/challenges/$id': typeof CandidateChallengesIdRoute
  '/candidate/jobs/$id': typeof CandidateJobsIdRoute
  '/candidate/challenges/': typeof CandidateChallengesIndexRoute
  '/candidate/jobs/': typeof CandidateJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book-demo': typeof BookDemoRoute
  '/demo': typeof DemoRoute
  '/for-candidates': typeof ForCandidatesRoute
  '/for-companies': typeof ForCompaniesRoute
  '/for-universities': typeof ForUniversitiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/certificates': typeof CandidateCertificatesRoute
  '/candidate/interview': typeof CandidateInterviewRoute
  '/candidate/messages': typeof CandidateMessagesRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/results': typeof CandidateResultsRoute
  '/candidate/roadmap': typeof CandidateRoadmapRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/company/analytics': typeof CompanyAnalyticsRoute
  '/company/billing': typeof CompanyBillingRoute
  '/company/campaigns': typeof CompanyCampaignsRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/challenge-builder': typeof CompanyChallengeBuilderRoute
  '/company/interviews': typeof CompanyInterviewsRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/library': typeof CompanyLibraryRoute
  '/company/messages': typeof CompanyMessagesRoute
  '/company/reports': typeof CompanyReportsRoute
  '/company/settings': typeof CompanySettingsRoute
  '/company/shortlists': typeof CompanyShortlistsRoute
  '/p/$id': typeof PIdRoute
  '/university/analytics': typeof UniversityAnalyticsRoute
  '/university/certificates': typeof UniversityCertificatesRoute
  '/university/challenges': typeof UniversityChallengesRoute
  '/university/evidence': typeof UniversityEvidenceRoute
  '/university/leaderboards': typeof UniversityLeaderboardsRoute
  '/university/messages': typeof UniversityMessagesRoute
  '/university/partnerships': typeof UniversityPartnershipsRoute
  '/university/settings': typeof UniversitySettingsRoute
  '/university/students': typeof UniversityStudentsRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/candidate': typeof CandidateIndexRoute
  '/company': typeof CompanyIndexRoute
  '/university': typeof UniversityIndexRoute
  '/candidate/challenges/$id': typeof CandidateChallengesIdRoute
  '/candidate/jobs/$id': typeof CandidateJobsIdRoute
  '/candidate/challenges': typeof CandidateChallengesIndexRoute
  '/candidate/jobs': typeof CandidateJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book-demo': typeof BookDemoRoute
  '/candidate': typeof CandidateRouteWithChildren
  '/company': typeof CompanyRouteWithChildren
  '/demo': typeof DemoRoute
  '/for-candidates': typeof ForCandidatesRoute
  '/for-companies': typeof ForCompaniesRoute
  '/for-universities': typeof ForUniversitiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/university': typeof UniversityRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/certificates': typeof CandidateCertificatesRoute
  '/candidate/challenges': typeof CandidateChallengesRouteWithChildren
  '/candidate/interview': typeof CandidateInterviewRoute
  '/candidate/jobs': typeof CandidateJobsRouteWithChildren
  '/candidate/messages': typeof CandidateMessagesRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/results': typeof CandidateResultsRoute
  '/candidate/roadmap': typeof CandidateRoadmapRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/company/analytics': typeof CompanyAnalyticsRoute
  '/company/billing': typeof CompanyBillingRoute
  '/company/campaigns': typeof CompanyCampaignsRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/challenge-builder': typeof CompanyChallengeBuilderRoute
  '/company/interviews': typeof CompanyInterviewsRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/library': typeof CompanyLibraryRoute
  '/company/messages': typeof CompanyMessagesRoute
  '/company/reports': typeof CompanyReportsRoute
  '/company/settings': typeof CompanySettingsRoute
  '/company/shortlists': typeof CompanyShortlistsRoute
  '/p/$id': typeof PIdRoute
  '/university/analytics': typeof UniversityAnalyticsRoute
  '/university/certificates': typeof UniversityCertificatesRoute
  '/university/challenges': typeof UniversityChallengesRoute
  '/university/evidence': typeof UniversityEvidenceRoute
  '/university/leaderboards': typeof UniversityLeaderboardsRoute
  '/university/messages': typeof UniversityMessagesRoute
  '/university/partnerships': typeof UniversityPartnershipsRoute
  '/university/settings': typeof UniversitySettingsRoute
  '/university/students': typeof UniversityStudentsRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/candidate/': typeof CandidateIndexRoute
  '/company/': typeof CompanyIndexRoute
  '/university/': typeof UniversityIndexRoute
  '/candidate/challenges/$id': typeof CandidateChallengesIdRoute
  '/candidate/jobs/$id': typeof CandidateJobsIdRoute
  '/candidate/challenges/': typeof CandidateChallengesIndexRoute
  '/candidate/jobs/': typeof CandidateJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/book-demo'
    | '/candidate'
    | '/company'
    | '/demo'
    | '/for-candidates'
    | '/for-companies'
    | '/for-universities'
    | '/sitemap.xml'
    | '/university'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/candidate/applications'
    | '/candidate/certificates'
    | '/candidate/challenges'
    | '/candidate/interview'
    | '/candidate/jobs'
    | '/candidate/messages'
    | '/candidate/notifications'
    | '/candidate/profile'
    | '/candidate/results'
    | '/candidate/roadmap'
    | '/candidate/settings'
    | '/company/analytics'
    | '/company/billing'
    | '/company/campaigns'
    | '/company/candidates'
    | '/company/challenge-builder'
    | '/company/interviews'
    | '/company/jobs'
    | '/company/library'
    | '/company/messages'
    | '/company/reports'
    | '/company/settings'
    | '/company/shortlists'
    | '/p/$id'
    | '/university/analytics'
    | '/university/certificates'
    | '/university/challenges'
    | '/university/evidence'
    | '/university/leaderboards'
    | '/university/messages'
    | '/university/partnerships'
    | '/university/settings'
    | '/university/students'
    | '/verify/$code'
    | '/candidate/'
    | '/company/'
    | '/university/'
    | '/candidate/challenges/$id'
    | '/candidate/jobs/$id'
    | '/candidate/challenges/'
    | '/candidate/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/book-demo'
    | '/demo'
    | '/for-candidates'
    | '/for-companies'
    | '/for-universities'
    | '/sitemap.xml'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/candidate/applications'
    | '/candidate/certificates'
    | '/candidate/interview'
    | '/candidate/messages'
    | '/candidate/notifications'
    | '/candidate/profile'
    | '/candidate/results'
    | '/candidate/roadmap'
    | '/candidate/settings'
    | '/company/analytics'
    | '/company/billing'
    | '/company/campaigns'
    | '/company/candidates'
    | '/company/challenge-builder'
    | '/company/interviews'
    | '/company/jobs'
    | '/company/library'
    | '/company/messages'
    | '/company/reports'
    | '/company/settings'
    | '/company/shortlists'
    | '/p/$id'
    | '/university/analytics'
    | '/university/certificates'
    | '/university/challenges'
    | '/university/evidence'
    | '/university/leaderboards'
    | '/university/messages'
    | '/university/partnerships'
    | '/university/settings'
    | '/university/students'
    | '/verify/$code'
    | '/candidate'
    | '/company'
    | '/university'
    | '/candidate/challenges/$id'
    | '/candidate/jobs/$id'
    | '/candidate/challenges'
    | '/candidate/jobs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/book-demo'
    | '/candidate'
    | '/company'
    | '/demo'
    | '/for-candidates'
    | '/for-companies'
    | '/for-universities'
    | '/sitemap.xml'
    | '/university'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/candidate/applications'
    | '/candidate/certificates'
    | '/candidate/challenges'
    | '/candidate/interview'
    | '/candidate/jobs'
    | '/candidate/messages'
    | '/candidate/notifications'
    | '/candidate/profile'
    | '/candidate/results'
    | '/candidate/roadmap'
    | '/candidate/settings'
    | '/company/analytics'
    | '/company/billing'
    | '/company/campaigns'
    | '/company/candidates'
    | '/company/challenge-builder'
    | '/company/interviews'
    | '/company/jobs'
    | '/company/library'
    | '/company/messages'
    | '/company/reports'
    | '/company/settings'
    | '/company/shortlists'
    | '/p/$id'
    | '/university/analytics'
    | '/university/certificates'
    | '/university/challenges'
    | '/university/evidence'
    | '/university/leaderboards'
    | '/university/messages'
    | '/university/partnerships'
    | '/university/settings'
    | '/university/students'
    | '/verify/$code'
    | '/candidate/'
    | '/company/'
    | '/university/'
    | '/candidate/challenges/$id'
    | '/candidate/jobs/$id'
    | '/candidate/challenges/'
    | '/candidate/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookDemoRoute: typeof BookDemoRoute
  CandidateRoute: typeof CandidateRouteWithChildren
  CompanyRoute: typeof CompanyRouteWithChildren
  DemoRoute: typeof DemoRoute
  ForCandidatesRoute: typeof ForCandidatesRoute
  ForCompaniesRoute: typeof ForCompaniesRoute
  ForUniversitiesRoute: typeof ForUniversitiesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UniversityRoute: typeof UniversityRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  PIdRoute: typeof PIdRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/university': {
      id: '/university'
      path: '/university'
      fullPath: '/university'
      preLoaderRoute: typeof UniversityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-universities': {
      id: '/for-universities'
      path: '/for-universities'
      fullPath: '/for-universities'
      preLoaderRoute: typeof ForUniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-companies': {
      id: '/for-companies'
      path: '/for-companies'
      fullPath: '/for-companies'
      preLoaderRoute: typeof ForCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-candidates': {
      id: '/for-candidates'
      path: '/for-candidates'
      fullPath: '/for-candidates'
      preLoaderRoute: typeof ForCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate': {
      id: '/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof CandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-demo': {
      id: '/book-demo'
      path: '/book-demo'
      fullPath: '/book-demo'
      preLoaderRoute: typeof BookDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university/': {
      id: '/university/'
      path: '/'
      fullPath: '/university/'
      preLoaderRoute: typeof UniversityIndexRouteImport
      parentRoute: typeof UniversityRoute
    }
    '/company/': {
      id: '/company/'
      path: '/'
      fullPath: '/company/'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/'
      fullPath: '/candidate/'
      preLoaderRoute: typeof CandidateIndexRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university/students': {
      id: '/university/students'
      path: '/students'
      fullPath: '/university/students'
      preLoaderRoute: typeof UniversityStudentsRouteImport
      parentRoute: typeof UniversityRoute
    }
    '/university/settings': {
      id: '/university/settings'
      path: '/settings'
      fullPath: '/university/settings'
      preLoaderRoute: typeof UniversitySettingsRouteImport
      parentRoute: typeof UniversityRoute
    }
    '/university/partnerships': {
      id: '/university/partnerships'
      path: '/partnerships'
      fullPath: '/university/partnerships'
      preLoaderRoute: typeof UniversityPartnershipsRouteImport
      parentRoute: typeof UniversityRoute
    }
    '/university/messages': {
      id: '/university/messages'
      path: '/messages'
      fullPath: '/university/messages'
      preLoaderRoute: typeof UniversityMessagesRouteImport
      parentRoute: typeof UniversityRoute
    }
    '/university/leaderboards': {
      id: '/university/leaderboards'
      path: '/leaderboards'
      fullPath: '/university/leaderboards'
      preLoaderRoute: typeof UniversityLeaderboardsRouteImport
      parentRoute: typeof UniversityRoute
    }
    '/university/evidence': {
      id: '/university/evidence'
      path: '/evidence'
      fullPath: '/university/evidence'
      preLoaderRoute: typeof UniversityEvidenceRouteImport
      parentRoute: typeof UniversityRoute
    }
    '/university/challenges': {
      id: '/university/challenges'
      path: '/challenges'
      fullPath: '/university/challenges'
      preLoaderRoute: typeof UniversityChallengesRouteImport
      parentRoute: typeof UniversityRoute
    }
    '/university/certificates': {
      id: '/university/certificates'
      path: '/certificates'
      fullPath: '/university/certificates'
      preLoaderRoute: typeof UniversityCertificatesRouteImport
      parentRoute: typeof UniversityRoute
    }
    '/university/analytics': {
      id: '/university/analytics'
      path: '/analytics'
      fullPath: '/university/analytics'
      preLoaderRoute: typeof UniversityAnalyticsRouteImport
      parentRoute: typeof UniversityRoute
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/shortlists': {
      id: '/company/shortlists'
      path: '/shortlists'
      fullPath: '/company/shortlists'
      preLoaderRoute: typeof CompanyShortlistsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/settings': {
      id: '/company/settings'
      path: '/settings'
      fullPath: '/company/settings'
      preLoaderRoute: typeof CompanySettingsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/reports': {
      id: '/company/reports'
      path: '/reports'
      fullPath: '/company/reports'
      preLoaderRoute: typeof CompanyReportsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/messages': {
      id: '/company/messages'
      path: '/messages'
      fullPath: '/company/messages'
      preLoaderRoute: typeof CompanyMessagesRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/library': {
      id: '/company/library'
      path: '/library'
      fullPath: '/company/library'
      preLoaderRoute: typeof CompanyLibraryRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/jobs': {
      id: '/company/jobs'
      path: '/jobs'
      fullPath: '/company/jobs'
      preLoaderRoute: typeof CompanyJobsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/interviews': {
      id: '/company/interviews'
      path: '/interviews'
      fullPath: '/company/interviews'
      preLoaderRoute: typeof CompanyInterviewsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/challenge-builder': {
      id: '/company/challenge-builder'
      path: '/challenge-builder'
      fullPath: '/company/challenge-builder'
      preLoaderRoute: typeof CompanyChallengeBuilderRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/candidates': {
      id: '/company/candidates'
      path: '/candidates'
      fullPath: '/company/candidates'
      preLoaderRoute: typeof CompanyCandidatesRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/campaigns': {
      id: '/company/campaigns'
      path: '/campaigns'
      fullPath: '/company/campaigns'
      preLoaderRoute: typeof CompanyCampaignsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/billing': {
      id: '/company/billing'
      path: '/billing'
      fullPath: '/company/billing'
      preLoaderRoute: typeof CompanyBillingRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/analytics': {
      id: '/company/analytics'
      path: '/analytics'
      fullPath: '/company/analytics'
      preLoaderRoute: typeof CompanyAnalyticsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/candidate/settings': {
      id: '/candidate/settings'
      path: '/settings'
      fullPath: '/candidate/settings'
      preLoaderRoute: typeof CandidateSettingsRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/roadmap': {
      id: '/candidate/roadmap'
      path: '/roadmap'
      fullPath: '/candidate/roadmap'
      preLoaderRoute: typeof CandidateRoadmapRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/results': {
      id: '/candidate/results'
      path: '/results'
      fullPath: '/candidate/results'
      preLoaderRoute: typeof CandidateResultsRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/notifications': {
      id: '/candidate/notifications'
      path: '/notifications'
      fullPath: '/candidate/notifications'
      preLoaderRoute: typeof CandidateNotificationsRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/messages': {
      id: '/candidate/messages'
      path: '/messages'
      fullPath: '/candidate/messages'
      preLoaderRoute: typeof CandidateMessagesRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/jobs': {
      id: '/candidate/jobs'
      path: '/jobs'
      fullPath: '/candidate/jobs'
      preLoaderRoute: typeof CandidateJobsRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/interview': {
      id: '/candidate/interview'
      path: '/interview'
      fullPath: '/candidate/interview'
      preLoaderRoute: typeof CandidateInterviewRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/challenges': {
      id: '/candidate/challenges'
      path: '/challenges'
      fullPath: '/candidate/challenges'
      preLoaderRoute: typeof CandidateChallengesRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/certificates': {
      id: '/candidate/certificates'
      path: '/certificates'
      fullPath: '/candidate/certificates'
      preLoaderRoute: typeof CandidateCertificatesRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/applications': {
      id: '/candidate/applications'
      path: '/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof CandidateApplicationsRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/jobs/': {
      id: '/candidate/jobs/'
      path: '/'
      fullPath: '/candidate/jobs/'
      preLoaderRoute: typeof CandidateJobsIndexRouteImport
      parentRoute: typeof CandidateJobsRoute
    }
    '/candidate/challenges/': {
      id: '/candidate/challenges/'
      path: '/'
      fullPath: '/candidate/challenges/'
      preLoaderRoute: typeof CandidateChallengesIndexRouteImport
      parentRoute: typeof CandidateChallengesRoute
    }
    '/candidate/jobs/$id': {
      id: '/candidate/jobs/$id'
      path: '/$id'
      fullPath: '/candidate/jobs/$id'
      preLoaderRoute: typeof CandidateJobsIdRouteImport
      parentRoute: typeof CandidateJobsRoute
    }
    '/candidate/challenges/$id': {
      id: '/candidate/challenges/$id'
      path: '/$id'
      fullPath: '/candidate/challenges/$id'
      preLoaderRoute: typeof CandidateChallengesIdRouteImport
      parentRoute: typeof CandidateChallengesRoute
    }
  }
}

interface CandidateChallengesRouteChildren {
  CandidateChallengesIdRoute: typeof CandidateChallengesIdRoute
  CandidateChallengesIndexRoute: typeof CandidateChallengesIndexRoute
}

const CandidateChallengesRouteChildren: CandidateChallengesRouteChildren = {
  CandidateChallengesIdRoute: CandidateChallengesIdRoute,
  CandidateChallengesIndexRoute: CandidateChallengesIndexRoute,
}

const CandidateChallengesRouteWithChildren =
  CandidateChallengesRoute._addFileChildren(CandidateChallengesRouteChildren)

interface CandidateJobsRouteChildren {
  CandidateJobsIdRoute: typeof CandidateJobsIdRoute
  CandidateJobsIndexRoute: typeof CandidateJobsIndexRoute
}

const CandidateJobsRouteChildren: CandidateJobsRouteChildren = {
  CandidateJobsIdRoute: CandidateJobsIdRoute,
  CandidateJobsIndexRoute: CandidateJobsIndexRoute,
}

const CandidateJobsRouteWithChildren = CandidateJobsRoute._addFileChildren(
  CandidateJobsRouteChildren,
)

interface CandidateRouteChildren {
  CandidateApplicationsRoute: typeof CandidateApplicationsRoute
  CandidateCertificatesRoute: typeof CandidateCertificatesRoute
  CandidateChallengesRoute: typeof CandidateChallengesRouteWithChildren
  CandidateInterviewRoute: typeof CandidateInterviewRoute
  CandidateJobsRoute: typeof CandidateJobsRouteWithChildren
  CandidateMessagesRoute: typeof CandidateMessagesRoute
  CandidateNotificationsRoute: typeof CandidateNotificationsRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  CandidateResultsRoute: typeof CandidateResultsRoute
  CandidateRoadmapRoute: typeof CandidateRoadmapRoute
  CandidateSettingsRoute: typeof CandidateSettingsRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
}

const CandidateRouteChildren: CandidateRouteChildren = {
  CandidateApplicationsRoute: CandidateApplicationsRoute,
  CandidateCertificatesRoute: CandidateCertificatesRoute,
  CandidateChallengesRoute: CandidateChallengesRouteWithChildren,
  CandidateInterviewRoute: CandidateInterviewRoute,
  CandidateJobsRoute: CandidateJobsRouteWithChildren,
  CandidateMessagesRoute: CandidateMessagesRoute,
  CandidateNotificationsRoute: CandidateNotificationsRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  CandidateResultsRoute: CandidateResultsRoute,
  CandidateRoadmapRoute: CandidateRoadmapRoute,
  CandidateSettingsRoute: CandidateSettingsRoute,
  CandidateIndexRoute: CandidateIndexRoute,
}

const CandidateRouteWithChildren = CandidateRoute._addFileChildren(
  CandidateRouteChildren,
)

interface CompanyRouteChildren {
  CompanyAnalyticsRoute: typeof CompanyAnalyticsRoute
  CompanyBillingRoute: typeof CompanyBillingRoute
  CompanyCampaignsRoute: typeof CompanyCampaignsRoute
  CompanyCandidatesRoute: typeof CompanyCandidatesRoute
  CompanyChallengeBuilderRoute: typeof CompanyChallengeBuilderRoute
  CompanyInterviewsRoute: typeof CompanyInterviewsRoute
  CompanyJobsRoute: typeof CompanyJobsRoute
  CompanyLibraryRoute: typeof CompanyLibraryRoute
  CompanyMessagesRoute: typeof CompanyMessagesRoute
  CompanyReportsRoute: typeof CompanyReportsRoute
  CompanySettingsRoute: typeof CompanySettingsRoute
  CompanyShortlistsRoute: typeof CompanyShortlistsRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
}

const CompanyRouteChildren: CompanyRouteChildren = {
  CompanyAnalyticsRoute: CompanyAnalyticsRoute,
  CompanyBillingRoute: CompanyBillingRoute,
  CompanyCampaignsRoute: CompanyCampaignsRoute,
  CompanyCandidatesRoute: CompanyCandidatesRoute,
  CompanyChallengeBuilderRoute: CompanyChallengeBuilderRoute,
  CompanyInterviewsRoute: CompanyInterviewsRoute,
  CompanyJobsRoute: CompanyJobsRoute,
  CompanyLibraryRoute: CompanyLibraryRoute,
  CompanyMessagesRoute: CompanyMessagesRoute,
  CompanyReportsRoute: CompanyReportsRoute,
  CompanySettingsRoute: CompanySettingsRoute,
  CompanyShortlistsRoute: CompanyShortlistsRoute,
  CompanyIndexRoute: CompanyIndexRoute,
}

const CompanyRouteWithChildren =
  CompanyRoute._addFileChildren(CompanyRouteChildren)

interface UniversityRouteChildren {
  UniversityAnalyticsRoute: typeof UniversityAnalyticsRoute
  UniversityCertificatesRoute: typeof UniversityCertificatesRoute
  UniversityChallengesRoute: typeof UniversityChallengesRoute
  UniversityEvidenceRoute: typeof UniversityEvidenceRoute
  UniversityLeaderboardsRoute: typeof UniversityLeaderboardsRoute
  UniversityMessagesRoute: typeof UniversityMessagesRoute
  UniversityPartnershipsRoute: typeof UniversityPartnershipsRoute
  UniversitySettingsRoute: typeof UniversitySettingsRoute
  UniversityStudentsRoute: typeof UniversityStudentsRoute
  UniversityIndexRoute: typeof UniversityIndexRoute
}

const UniversityRouteChildren: UniversityRouteChildren = {
  UniversityAnalyticsRoute: UniversityAnalyticsRoute,
  UniversityCertificatesRoute: UniversityCertificatesRoute,
  UniversityChallengesRoute: UniversityChallengesRoute,
  UniversityEvidenceRoute: UniversityEvidenceRoute,
  UniversityLeaderboardsRoute: UniversityLeaderboardsRoute,
  UniversityMessagesRoute: UniversityMessagesRoute,
  UniversityPartnershipsRoute: UniversityPartnershipsRoute,
  UniversitySettingsRoute: UniversitySettingsRoute,
  UniversityStudentsRoute: UniversityStudentsRoute,
  UniversityIndexRoute: UniversityIndexRoute,
}

const UniversityRouteWithChildren = UniversityRoute._addFileChildren(
  UniversityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookDemoRoute: BookDemoRoute,
  CandidateRoute: CandidateRouteWithChildren,
  CompanyRoute: CompanyRouteWithChildren,
  DemoRoute: DemoRoute,
  ForCandidatesRoute: ForCandidatesRoute,
  ForCompaniesRoute: ForCompaniesRoute,
  ForUniversitiesRoute: ForUniversitiesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UniversityRoute: UniversityRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  PIdRoute: PIdRoute,
  VerifyCodeRoute: VerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
