/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CompanyDemoRouteImport } from './routes/company-demo'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CandidateDemoRouteImport } from './routes/candidate-demo'
import { Route as CandidateRouteImport } from './routes/candidate'
import { Route as BookDemoRouteImport } from './routes/book-demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyIndexRouteImport } from './routes/company.index'
import { Route as CandidateIndexRouteImport } from './routes/candidate.index'
import { Route as CompanySettingsRouteImport } from './routes/company.settings'
import { Route as CompanyReportsRouteImport } from './routes/company.reports'
import { Route as CompanyMessagesRouteImport } from './routes/company.messages'
import { Route as CompanyInterviewsRouteImport } from './routes/company.interviews'
import { Route as CompanyChallengeBuilderRouteImport } from './routes/company.challenge-builder'
import { Route as CompanyCandidatesRouteImport } from './routes/company.candidates'
import { Route as CompanyCampaignsRouteImport } from './routes/company.campaigns'
import { Route as CompanyBillingRouteImport } from './routes/company.billing'
import { Route as CompanyAnalyticsRouteImport } from './routes/company.analytics'
import { Route as CandidateSettingsRouteImport } from './routes/candidate.settings'
import { Route as CandidateRoadmapRouteImport } from './routes/candidate.roadmap'
import { Route as CandidateProfileRouteImport } from './routes/candidate.profile'
import { Route as CandidateJobsRouteImport } from './routes/candidate.jobs'
import { Route as CandidateInterviewRouteImport } from './routes/candidate.interview'
import { Route as CandidateChallengesRouteImport } from './routes/candidate.challenges'
import { Route as CandidateCertificatesRouteImport } from './routes/candidate.certificates'
import { Route as CandidateApplicationsRouteImport } from './routes/candidate.applications'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyDemoRoute = CompanyDemoRouteImport.update({
  id: '/company-demo',
  path: '/company-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateDemoRoute = CandidateDemoRouteImport.update({
  id: '/candidate-demo',
  path: '/candidate-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateRoute = CandidateRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDemoRoute = BookDemoRouteImport.update({
  id: '/book-demo',
  path: '/book-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanyRoute,
} as any)
const CandidateIndexRoute = CandidateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CandidateRoute,
} as any)
const CompanySettingsRoute = CompanySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyReportsRoute = CompanyReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyMessagesRoute = CompanyMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyInterviewsRoute = CompanyInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyChallengeBuilderRoute = CompanyChallengeBuilderRouteImport.update({
  id: '/challenge-builder',
  path: '/challenge-builder',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyCandidatesRoute = CompanyCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyCampaignsRoute = CompanyCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyBillingRoute = CompanyBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyAnalyticsRoute = CompanyAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => CompanyRoute,
} as any)
const CandidateSettingsRoute = CandidateSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateRoadmapRoute = CandidateRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateJobsRoute = CandidateJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateInterviewRoute = CandidateInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateChallengesRoute = CandidateChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateCertificatesRoute = CandidateCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateApplicationsRoute = CandidateApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => CandidateRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book-demo': typeof BookDemoRoute
  '/candidate': typeof CandidateRouteWithChildren
  '/candidate-demo': typeof CandidateDemoRoute
  '/company': typeof CompanyRouteWithChildren
  '/company-demo': typeof CompanyDemoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/certificates': typeof CandidateCertificatesRoute
  '/candidate/challenges': typeof CandidateChallengesRoute
  '/candidate/interview': typeof CandidateInterviewRoute
  '/candidate/jobs': typeof CandidateJobsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/roadmap': typeof CandidateRoadmapRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/company/analytics': typeof CompanyAnalyticsRoute
  '/company/billing': typeof CompanyBillingRoute
  '/company/campaigns': typeof CompanyCampaignsRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/challenge-builder': typeof CompanyChallengeBuilderRoute
  '/company/interviews': typeof CompanyInterviewsRoute
  '/company/messages': typeof CompanyMessagesRoute
  '/company/reports': typeof CompanyReportsRoute
  '/company/settings': typeof CompanySettingsRoute
  '/candidate/': typeof CandidateIndexRoute
  '/company/': typeof CompanyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-demo': typeof BookDemoRoute
  '/candidate-demo': typeof CandidateDemoRoute
  '/company-demo': typeof CompanyDemoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/certificates': typeof CandidateCertificatesRoute
  '/candidate/challenges': typeof CandidateChallengesRoute
  '/candidate/interview': typeof CandidateInterviewRoute
  '/candidate/jobs': typeof CandidateJobsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/roadmap': typeof CandidateRoadmapRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/company/analytics': typeof CompanyAnalyticsRoute
  '/company/billing': typeof CompanyBillingRoute
  '/company/campaigns': typeof CompanyCampaignsRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/challenge-builder': typeof CompanyChallengeBuilderRoute
  '/company/interviews': typeof CompanyInterviewsRoute
  '/company/messages': typeof CompanyMessagesRoute
  '/company/reports': typeof CompanyReportsRoute
  '/company/settings': typeof CompanySettingsRoute
  '/candidate': typeof CandidateIndexRoute
  '/company': typeof CompanyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book-demo': typeof BookDemoRoute
  '/candidate': typeof CandidateRouteWithChildren
  '/candidate-demo': typeof CandidateDemoRoute
  '/company': typeof CompanyRouteWithChildren
  '/company-demo': typeof CompanyDemoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/certificates': typeof CandidateCertificatesRoute
  '/candidate/challenges': typeof CandidateChallengesRoute
  '/candidate/interview': typeof CandidateInterviewRoute
  '/candidate/jobs': typeof CandidateJobsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/roadmap': typeof CandidateRoadmapRoute
  '/candidate/settings': typeof CandidateSettingsRoute
  '/company/analytics': typeof CompanyAnalyticsRoute
  '/company/billing': typeof CompanyBillingRoute
  '/company/campaigns': typeof CompanyCampaignsRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/challenge-builder': typeof CompanyChallengeBuilderRoute
  '/company/interviews': typeof CompanyInterviewsRoute
  '/company/messages': typeof CompanyMessagesRoute
  '/company/reports': typeof CompanyReportsRoute
  '/company/settings': typeof CompanySettingsRoute
  '/candidate/': typeof CandidateIndexRoute
  '/company/': typeof CompanyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book-demo'
    | '/candidate'
    | '/candidate-demo'
    | '/company'
    | '/company-demo'
    | '/sitemap.xml'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/candidate/applications'
    | '/candidate/certificates'
    | '/candidate/challenges'
    | '/candidate/interview'
    | '/candidate/jobs'
    | '/candidate/profile'
    | '/candidate/roadmap'
    | '/candidate/settings'
    | '/company/analytics'
    | '/company/billing'
    | '/company/campaigns'
    | '/company/candidates'
    | '/company/challenge-builder'
    | '/company/interviews'
    | '/company/messages'
    | '/company/reports'
    | '/company/settings'
    | '/candidate/'
    | '/company/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book-demo'
    | '/candidate-demo'
    | '/company-demo'
    | '/sitemap.xml'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/candidate/applications'
    | '/candidate/certificates'
    | '/candidate/challenges'
    | '/candidate/interview'
    | '/candidate/jobs'
    | '/candidate/profile'
    | '/candidate/roadmap'
    | '/candidate/settings'
    | '/company/analytics'
    | '/company/billing'
    | '/company/campaigns'
    | '/company/candidates'
    | '/company/challenge-builder'
    | '/company/interviews'
    | '/company/messages'
    | '/company/reports'
    | '/company/settings'
    | '/candidate'
    | '/company'
  id:
    | '__root__'
    | '/'
    | '/book-demo'
    | '/candidate'
    | '/candidate-demo'
    | '/company'
    | '/company-demo'
    | '/sitemap.xml'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/candidate/applications'
    | '/candidate/certificates'
    | '/candidate/challenges'
    | '/candidate/interview'
    | '/candidate/jobs'
    | '/candidate/profile'
    | '/candidate/roadmap'
    | '/candidate/settings'
    | '/company/analytics'
    | '/company/billing'
    | '/company/campaigns'
    | '/company/candidates'
    | '/company/challenge-builder'
    | '/company/interviews'
    | '/company/messages'
    | '/company/reports'
    | '/company/settings'
    | '/candidate/'
    | '/company/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookDemoRoute: typeof BookDemoRoute
  CandidateRoute: typeof CandidateRouteWithChildren
  CandidateDemoRoute: typeof CandidateDemoRoute
  CompanyRoute: typeof CompanyRouteWithChildren
  CompanyDemoRoute: typeof CompanyDemoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-demo': {
      id: '/company-demo'
      path: '/company-demo'
      fullPath: '/company-demo'
      preLoaderRoute: typeof CompanyDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate-demo': {
      id: '/candidate-demo'
      path: '/candidate-demo'
      fullPath: '/candidate-demo'
      preLoaderRoute: typeof CandidateDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate': {
      id: '/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof CandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-demo': {
      id: '/book-demo'
      path: '/book-demo'
      fullPath: '/book-demo'
      preLoaderRoute: typeof BookDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/': {
      id: '/company/'
      path: '/'
      fullPath: '/company/'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/'
      fullPath: '/candidate/'
      preLoaderRoute: typeof CandidateIndexRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/company/settings': {
      id: '/company/settings'
      path: '/settings'
      fullPath: '/company/settings'
      preLoaderRoute: typeof CompanySettingsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/reports': {
      id: '/company/reports'
      path: '/reports'
      fullPath: '/company/reports'
      preLoaderRoute: typeof CompanyReportsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/messages': {
      id: '/company/messages'
      path: '/messages'
      fullPath: '/company/messages'
      preLoaderRoute: typeof CompanyMessagesRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/interviews': {
      id: '/company/interviews'
      path: '/interviews'
      fullPath: '/company/interviews'
      preLoaderRoute: typeof CompanyInterviewsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/challenge-builder': {
      id: '/company/challenge-builder'
      path: '/challenge-builder'
      fullPath: '/company/challenge-builder'
      preLoaderRoute: typeof CompanyChallengeBuilderRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/candidates': {
      id: '/company/candidates'
      path: '/candidates'
      fullPath: '/company/candidates'
      preLoaderRoute: typeof CompanyCandidatesRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/campaigns': {
      id: '/company/campaigns'
      path: '/campaigns'
      fullPath: '/company/campaigns'
      preLoaderRoute: typeof CompanyCampaignsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/billing': {
      id: '/company/billing'
      path: '/billing'
      fullPath: '/company/billing'
      preLoaderRoute: typeof CompanyBillingRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/analytics': {
      id: '/company/analytics'
      path: '/analytics'
      fullPath: '/company/analytics'
      preLoaderRoute: typeof CompanyAnalyticsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/candidate/settings': {
      id: '/candidate/settings'
      path: '/settings'
      fullPath: '/candidate/settings'
      preLoaderRoute: typeof CandidateSettingsRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/roadmap': {
      id: '/candidate/roadmap'
      path: '/roadmap'
      fullPath: '/candidate/roadmap'
      preLoaderRoute: typeof CandidateRoadmapRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/jobs': {
      id: '/candidate/jobs'
      path: '/jobs'
      fullPath: '/candidate/jobs'
      preLoaderRoute: typeof CandidateJobsRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/interview': {
      id: '/candidate/interview'
      path: '/interview'
      fullPath: '/candidate/interview'
      preLoaderRoute: typeof CandidateInterviewRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/challenges': {
      id: '/candidate/challenges'
      path: '/challenges'
      fullPath: '/candidate/challenges'
      preLoaderRoute: typeof CandidateChallengesRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/certificates': {
      id: '/candidate/certificates'
      path: '/certificates'
      fullPath: '/candidate/certificates'
      preLoaderRoute: typeof CandidateCertificatesRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/applications': {
      id: '/candidate/applications'
      path: '/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof CandidateApplicationsRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CandidateRouteChildren {
  CandidateApplicationsRoute: typeof CandidateApplicationsRoute
  CandidateCertificatesRoute: typeof CandidateCertificatesRoute
  CandidateChallengesRoute: typeof CandidateChallengesRoute
  CandidateInterviewRoute: typeof CandidateInterviewRoute
  CandidateJobsRoute: typeof CandidateJobsRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  CandidateRoadmapRoute: typeof CandidateRoadmapRoute
  CandidateSettingsRoute: typeof CandidateSettingsRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
}

const CandidateRouteChildren: CandidateRouteChildren = {
  CandidateApplicationsRoute: CandidateApplicationsRoute,
  CandidateCertificatesRoute: CandidateCertificatesRoute,
  CandidateChallengesRoute: CandidateChallengesRoute,
  CandidateInterviewRoute: CandidateInterviewRoute,
  CandidateJobsRoute: CandidateJobsRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  CandidateRoadmapRoute: CandidateRoadmapRoute,
  CandidateSettingsRoute: CandidateSettingsRoute,
  CandidateIndexRoute: CandidateIndexRoute,
}

const CandidateRouteWithChildren = CandidateRoute._addFileChildren(
  CandidateRouteChildren,
)

interface CompanyRouteChildren {
  CompanyAnalyticsRoute: typeof CompanyAnalyticsRoute
  CompanyBillingRoute: typeof CompanyBillingRoute
  CompanyCampaignsRoute: typeof CompanyCampaignsRoute
  CompanyCandidatesRoute: typeof CompanyCandidatesRoute
  CompanyChallengeBuilderRoute: typeof CompanyChallengeBuilderRoute
  CompanyInterviewsRoute: typeof CompanyInterviewsRoute
  CompanyMessagesRoute: typeof CompanyMessagesRoute
  CompanyReportsRoute: typeof CompanyReportsRoute
  CompanySettingsRoute: typeof CompanySettingsRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
}

const CompanyRouteChildren: CompanyRouteChildren = {
  CompanyAnalyticsRoute: CompanyAnalyticsRoute,
  CompanyBillingRoute: CompanyBillingRoute,
  CompanyCampaignsRoute: CompanyCampaignsRoute,
  CompanyCandidatesRoute: CompanyCandidatesRoute,
  CompanyChallengeBuilderRoute: CompanyChallengeBuilderRoute,
  CompanyInterviewsRoute: CompanyInterviewsRoute,
  CompanyMessagesRoute: CompanyMessagesRoute,
  CompanyReportsRoute: CompanyReportsRoute,
  CompanySettingsRoute: CompanySettingsRoute,
  CompanyIndexRoute: CompanyIndexRoute,
}

const CompanyRouteWithChildren =
  CompanyRoute._addFileChildren(CompanyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookDemoRoute: BookDemoRoute,
  CandidateRoute: CandidateRouteWithChildren,
  CandidateDemoRoute: CandidateDemoRoute,
  CompanyRoute: CompanyRouteWithChildren,
  CompanyDemoRoute: CompanyDemoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
